openapi: 3.0.0
info:
  title: Environment Config Service API
  description: API для управления конфигурациями различных окружений
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local development server
paths:
  /health:
    get:
      summary: Health check
      tags: [Health]
      responses:
        '200':
          description: Сервис работает
  /configs/{env}:
    get:
      summary: Получить все конфигурации окружения
      tags: [Configs]
      parameters:
        - name: env
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Список конфигураций
  /configs/{env}/{key}:
    get:
      summary: Получить конфигурацию
      tags: [Configs]
      parameters:
        - name: env
          in: path
          required: true
        - name: key
          in: path
          required: true
      responses:
        '200':
          description: Конфигурация найдена
        '404':
          description: Конфигурация не найдена
    post:
      summary: Создать конфигурацию
      tags: [Configs]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [value]
              properties:
                value:
                  type: string
      responses:
        '201':
          description: Конфигурация создана
        '409':
          description: Конфигурация уже существует
    put:
      summary: Обновить конфигурацию
      tags: [Configs]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [value]
              properties:
                value:
                  type: string
      responses:
        '204':
          description: Конфигурация обновлена
        '404':
          description: Конфигурация не найдена
    delete:
      summary: Удалить конфигурацию
      tags: [Configs]
      responses:
        '204':
          description: Конфигурация удалена
        '404':
          description: Конфигурация не найдена
components:
  schemas:
    Config:
      type: object
      properties:
        env:
          type: string
        key:
          type: string
        value:
          type: string
        updated_at:
          type: string
          format: date-time

