name: CI

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'frontend/**'
      - '.github/actions/docker-setup/**'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - 'backend/**'
      - 'frontend/**'
      - '.github/actions/docker-setup/**'
      - '.github/workflows/ci.yml'

jobs:
  backend_lint:
    name: Backend Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - run: go mod download
        working-directory: ./backend

      - run: go fmt ./...
        working-directory: ./backend

      - run: go vet ./...
        working-directory: ./backend

  backend_test:
    name: Backend Test
    runs-on: ubuntu-latest
    needs: backend_lint

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - run: go mod download
        working-directory: ./backend

      - run: go test -v ./...
        working-directory: ./backend
        
  sonar_backend:
    name: SonarQube Backend Analysis
    runs-on: ubuntu-latest
    needs: backend_test
    environment: Base

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install dependencies
        working-directory: ./backend
        run: go mod download

      - name: Run tests with coverage
        working-directory: ./backend
        run: go test -coverpkg=./... ./... -coverprofile=coverage.out

      - name: SonarQube Scan (Backend)
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACKEND }}
        with:
          args: >
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            -Dsonar.projectKey=devops-lab
            -Dsonar.projectName=devops-lab
            -Dsonar.sources=cmd,config,internal,pkg
            -Dsonar.exclusions=**/*_test.go,internal/handler/doc.*,internal/infrastructure/database/queries/**
            -Dsonar.coverage.exclusions=**/*_test.go,cmd/**,internal/di/**,pkg/server/**
            -Dsonar.cpd.exclusions=**/*_test.go
            -Dsonar.projectBaseDir=backend
            -Dsonar.go.coverage.reportPaths=coverage.out
            -Dsonar.working.directory=.scannerwork

      - name: Quality Gate (fail CI if not OK)
        run: |
          echo "Waiting for SonarQube Quality Gate..."

          STATUS="PENDING"

          until [ "$STATUS" = "OK" ] || [ "$STATUS" = "ERROR" ]; do
            RESPONSE=$(curl -s -u ${{ secrets.SONAR_TOKEN_BACKEND }}: \
              "${{ secrets.SONAR_HOST_URL }}/api/qualitygates/project_status?projectKey=devops-lab")

            echo "$RESPONSE"

            STATUS=$(echo "$RESPONSE" | jq -r '.projectStatus.status // "NONE"')

            echo "Current status: $STATUS"
            sleep 5
          done

          if [ "$STATUS" != "OK" ]; then
            echo "Quality Gate FAILED"
            exit 1
          fi

          echo "Quality Gate PASSED"

  backend_build:
    name: Backend Build
    runs-on: ubuntu-latest
    needs: sonar_backend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - run: go mod download
        working-directory: ./backend

      - run: go build -v ./...
        working-directory: ./backend

  frontend_lint:
    name: Frontend Lint
    runs-on: ubuntu-latest
    needs: backend_build

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: npm install
        working-directory: ./frontend

      - run: npm run lint
        working-directory: ./frontend

  frontend_test:
    name: Frontend Test
    runs-on: ubuntu-latest
    needs: frontend_lint

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: npm install
        working-directory: ./frontend

      - run: npm test
        working-directory: ./frontend


  sonar_frontend:
    name: SonarQube Frontend Analysis
    runs-on: ubuntu-latest
    needs: frontend_test
    environment: Base

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run tests with coverage
        working-directory: ./frontend
        run: npm test -- --coverage

      - name: SonarQube Scan (Frontend)
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONTEND }}
        with:
          args: >
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            -Dsonar.projectKey=devops-lab-frontend
            -Dsonar.projectName=devops-lab-frontend
            -Dsonar.sources=src
            -Dsonar.projectBaseDir=frontend
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.working.directory=.scannerwork

      - name: Quality Gate (Frontend)
        run: |
          echo "Waiting for SonarQube Quality Gate..."

          STATUS="PENDING"

          until [ "$STATUS" = "OK" ] || [ "$STATUS" = "ERROR" ]; do
            RESPONSE=$(curl -s -u ${{ secrets.SONAR_TOKEN_FRONTEND }}: \
              "${{ secrets.SONAR_HOST_URL }}/api/qualitygates/project_status?projectKey=devops-lab-frontend")

            STATUS=$(echo "$RESPONSE" | jq -r '.projectStatus.status // "NONE"')

            echo "Frontend Quality Gate: $STATUS"
            sleep 5
          done

          if [ "$STATUS" != "OK" ]; then
            echo "Frontend Quality Gate FAILED"
            exit 1
          fi

          echo "Frontend Quality Gate PASSED"

  frontend_build:
    name: Frontend Build
    runs-on: ubuntu-latest
    needs: sonar_frontend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: npm install
        working-directory: ./frontend

      - run: npm run build
        working-directory: ./frontend

  publish_backend:
    name: Publish Backend Image
    runs-on: ubuntu-latest
    needs: backend_build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/docker-setup
        with:
          service: backend

  publish_frontend:
    name: Publish Frontend Image
    runs-on: ubuntu-latest
    needs: frontend_build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/docker-setup
        with:
          service: frontend
